# Generated by Django 4.2.25 on 2025-12-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingaddress_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
